### ISSUE TITLE
Seeking the stream doesn't work

### ISSUE THREAD

**Issue by benticlaskaris** [evilsephiroth/plugin.video.vvvvid#1]
Seeking a stream doesn't work due to ffmpeg and absence of subsequent ranged request from xbmc

**Comment by dentaku65** [comment]
Hi, I like very much your plugin, but as far as I can see seems that the contents are limited, for example no next page is available... it is my impression or vvvvid do not have much content?

**Comment by benticlaskaris** [comment]
well,vvvvid doesn't have a larger selection due to content rights in Italy. All materials on web site is present in the plugin
