### ISSUE TITLE
The Plugin doesn't work (Raspberry b+ with OBMC, last version)

### ISSUE THREAD

**Issue by Giusep502** [evilsephiroth/plugin.video.vvvvid#2]
I can see the list and the episodes of the show, but when i open an episode it doesn't start...

**Comment by benticlaskaris** [comment]
vvvvid changed url coding to retrieve media file  so this will be changed in next version of plugin

**Comment by benticlaskaris** [comment]
log would be appreciated

**Comment by Giusep502** [comment]
Thanks for the reply! I am a noob, is this log ok? 

11:37:56 T:2680849440  NOTICE: [xbmcswift2] Request for "/" matches rule for function "show_main_channels"
11:37:56 T:2795238432  NOTICE: Thread BackgroundLoader start, auto delete: false
11:37:59 T:2680849440  NOTICE: Thread LanguageInvoker start, auto delete: false
11:38:00 T:2680849440  NOTICE: -->Python Interpreter Initialized<--
11:38:05 T:2680849440  NOTICE: pycrypt not available using slow decryption
11:38:07 T:2680849440  NOTICE: [xbmcswift2] Request for "/anime/channels" matches rule for function "showAnimeChannels"
11:38:08 T:2744120352  NOTICE: Thread BackgroundLoader start, auto delete: false
11:38:10 T:2680849440  NOTICE: Thread LanguageInvoker start, auto delete: false
11:38:10 T:2680849440  NOTICE: -->Python Interpreter Initialized<--
11:38:13 T:2680849440  NOTICE: pycrypt not available using slow decryption
11:38:16 T:2680849440  NOTICE: [xbmcswift2] Request for "/anime/channel/10007" matches rule for function "showAnimeSingleChannel"
11:38:17 T:2744120352  NOTICE: Thread BackgroundLoader start, auto delete: false
11:38:19 T:2795238432  NOTICE: Thread LanguageInvoker start, auto delete: false
11:38:19 T:2795238432  NOTICE: -->Python Interpreter Initialized<--
11:38:22 T:2795238432  NOTICE: pycrypt not available using slow decryption
11:38:25 T:2795238432  NOTICE: [xbmcswift2] Request for "/anime/item/68" matches rule for function "showSingleAnimeItem"
11:38:27 T:2744120352  NOTICE: Thread BackgroundLoader start, auto delete: false
11:38:28 T:2744120352  NOTICE: Thread JobWorker start, auto delete: true
11:38:30 T:2680849440  NOTICE: Previous line repeats 1 times.
11:38:30 T:2680849440  NOTICE: Thread LanguageInvoker start, auto delete: false
11:38:30 T:2680849440  NOTICE: -->Python Interpreter Initialized<--
11:38:33 T:2680849440  NOTICE: pycrypt not available using slow decryption
11:38:36 T:2680849440  NOTICE: [xbmcswift2] Request for "/watch/http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41/01+-+Rinascita" matches rule for function "playManifest"
11:38:36 T:2680849440  NOTICE: http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/master.m3u8?g=DRIEGSYPNOBI&hdcore=3.6.0&plugin=aasp-3.6.0.50.41
11:38:36 T:2680849440  NOTICE: Previous line repeats 6 times.
11:38:36 T:2680849440  NOTICE: URL: http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/master.m3u8?g=DRIEGSYPNOBI&hdcore=3.6.0&plugin=aasp-3.6.0.50.41
11:38:36 T:2636903456  NOTICE: port
11:38:36 T:2636903456  NOTICE: 50000
11:38:36 T:2636903456  NOTICE: HOST_NAME
11:38:36 T:2636903456  NOTICE: 127.0.0.1
11:38:36 T:2636903456  NOTICE: XBMCLocalProxy Starts - 127.0.0.1:50000
11:38:37 T:2680849440  NOTICE: Now im playing... http://127.0.0.1:50000/url=http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41
11:38:37 T:2680849440  NOTICE: Sleeping...
11:38:37 T:2636903456  NOTICE: getSocket
11:38:37 T:2626679840   ERROR: 127.0.0.1 - - [24/Jul/2015 11:38:37] "HEAD /url=http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41 HTTP/1.1" 200 -
11:38:37 T:2626679840  NOTICE: XBMCLocalProxy: Serving HEAD request...
11:38:38 T:2680849440  NOTICE: Sleeping...
11:38:38 T:3023721008  NOTICE: DVDPlayer: Opening: http://127.0.0.1:50000/url=http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41
11:38:38 T:3023721008 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:38:38 T:2593457184  NOTICE: Thread DVDPlayer start, auto delete: false
11:38:38 T:2601845792  NOTICE: Thread CMMALRenderer start, auto delete: false
11:38:38 T:2593457184  NOTICE: Creating InputStream
11:38:38 T:2626679840   ERROR: 127.0.0.1 - - [24/Jul/2015 11:38:38] "HEAD /url=http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41 HTTP/1.1" 200 -
11:38:38 T:2626679840  NOTICE: XBMCLocalProxy: Serving HEAD request...
11:38:38 T:2636903456  NOTICE: getSocket
11:38:38 T:2558850080  NOTICE: XBMCLocalProxy: Serving GET request...
11:38:38 T:2558850080  NOTICE: in params
11:38:38 T:2558850080  NOTICE: params
11:38:38 T:2558850080  NOTICE: {'url': ['http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/master.m3u8?g=DRIEGSYPNOBI&hdcore=3.6.0&plugin=aasp-3.6.0.50.41']}
11:38:38 T:2558850080  NOTICE: simpledownloaderxxxxxxxxxxxxxxx
11:38:38 T:2558850080  NOTICE: False
11:38:38 T:2558850080  NOTICE: Url received at proxy
11:38:38 T:2558850080  NOTICE: http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/master.m3u8?g=DRIEGSYPNOBI&hdcore=3.6.0&plugin=aasp-3.6.0.50.41
11:38:38 T:2558850080  NOTICE: None
11:38:38 T:2558850080  NOTICE: False
11:38:38 T:2558850080  NOTICE: 0
11:38:38 T:2558850080  NOTICE: Downloading f4m manifest
11:38:38 T:2558850080  NOTICE: url
11:38:38 T:2558850080  NOTICE: http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/master.m3u8?g=DRIEGSYPNOBI&hdcore=3.6.0&plugin=aasp-3.6.0.50.41
11:38:38 T:2558850080  NOTICE: urlafter
11:38:38 T:2558850080  NOTICE: http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/master.m3u8?g=DRIEGSYPNOBI&hdcore=3.6.0&plugin=aasp-3.6.0.50.41
11:38:38 T:2680849440  NOTICE: Sleeping...
11:38:38 T:2558850080  NOTICE: Previous line repeats 1 times.
11:38:38 T:2558850080  NOTICE: 198
11:38:38 T:2558850080  NOTICE: #EXTM3U
                                            #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=731000,RESOLUTION=720x404,CODECS="avc1.77.30, mp4a.40.2"
                                            http://vvvvid-vh.akamaihd.net/i/Dynit/DEATH_NOTE/DEATH_NOTE_EP01m.mp4/index_0_av.m3u8?null=
11:38:38 T:2558850080   ERROR: Traceback (most recent call last):
11:38:38 T:2558850080   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.vvvvid-master/resources/lib/f4mDownloader.py", line 445, in preDownoload
11:38:38 T:2558850080   ERROR:     F4Mversion =re.findall(version_fine, manifest)[0]
11:38:38 T:2558850080   ERROR: IndexError: list index out of range
11:38:38 T:2558850080  NOTICE: cannot init
11:38:38 T:2680849440  NOTICE: Sleeping...
11:38:58 T:2593457184  NOTICE: Previous line repeats 97 times.
11:38:58 T:2593457184   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
11:38:58 T:2593457184   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
11:38:58 T:2593457184   ERROR: Open - failed to open source http://127.0.0.1:50000/url=http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41
11:38:58 T:2593457184   ERROR: CDVDPlayer::OpenInputStream - error opening [http://127.0.0.1:50000/url=http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41]
11:38:58 T:2593457184  NOTICE: CDVDPlayer::OnExit()
11:38:58 T:2680849440  NOTICE: seting event in onPlayBackStopped
11:38:58 T:2680849440  NOTICE: stop Event is SET
11:38:58 T:2636903456  NOTICE: XBMCLocalProxy Stops 127.0.0.1:50000
11:38:58 T:3023721008   ERROR: GetDirectory - Error getting plugin://plugin.video.vvvvid/watch/http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41/01+-+Rinascita
11:38:58 T:3023721008   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vvvvid/watch/http%3A%2F%2Fvvvvid-vh.akamaihd.net%2Fi%2FDynit%2FDEATH_NOTE%2FDEATH_NOTE_EP01m.mp4%2Fmaster.m3u8%3Fg%3DDRIEGSYPNOBI%26hdcore%3D3.6.0%26plugin%3Daasp-3.6.0.50.41/01+-+Rinascita) failed
11:38:58 T:2636903456  NOTICE: Thread BackgroundLoader start, auto delete: false
11:38:58 T:3023721008  NOTICE: CDVDPlayer::CloseFile()
11:38:58 T:3023721008  NOTICE: DVDPlayer: waiting for threads to exit
11:38:58 T:3023721008  NOTICE: DVDPlayer: finished waiting
11:38:58 T:3023721008  NOTICE: CDVDPlayer::CloseFile()
11:38:58 T:3023721008  NOTICE: DVDPlayer: waiting for threads to exit
11:38:58 T:3023721008  NOTICE: DVDPlayer: finished waiting
11:38:58 T:3023713312  NOTICE: Found 1 Lists of Devices
11:38:58 T:3023713312  NOTICE: Enumerated PI devices:
11:38:58 T:3023713312  NOTICE:     Device 1
11:38:58 T:3023713312  NOTICE:         m_deviceName      : HDMI
11:38:58 T:3023713312  NOTICE:         m_displayName     : HDMI
11:38:58 T:3023713312  NOTICE:         m_displayNameExtra:
11:38:58 T:3023713312  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
11:38:58 T:3023713312  NOTICE:         m_channels        : FL,FR
11:38:58 T:3023713312  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
11:38:58 T:3023713312  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
11:38:58 T:3023713312  NOTICE:     Device 2
11:38:58 T:3023713312  NOTICE:         m_deviceName      : Analogue
11:38:58 T:3023713312  NOTICE:         m_displayName     : Analogue
11:38:58 T:3023713312  NOTICE:         m_displayNameExtra:
11:38:58 T:3023713312  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:38:58 T:3023713312  NOTICE:         m_channels        : FL,FR
11:38:58 T:3023713312  NOTICE:         m_sampleRates     : 48000
11:38:58 T:3023713312  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
11:38:58 T:3023713312  NOTICE:     Device 3
11:38:58 T:3023713312  NOTICE:         m_deviceName      : Both
11:38:58 T:3023713312  NOTICE:         m_displayName     : HDMI and Analogue
11:38:58 T:3023713312  NOTICE:         m_displayNameExtra:
11:38:58 T:3023713312  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:38:58 T:3023713312  NOTICE:         m_channels        : FL,FR
11:38:58 T:3023713312  NOTICE:         m_sampleRates     : 48000
11:38:58 T:3023713312  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
11:38:59 T:2611471392  NOTICE: Thread JobWorker start, auto delete: true
11:39:08 T:2636903456  NOTICE: Thread BackgroundLoader start, auto delete: false
11:39:10 T:2558850080  NOTICE: Thread LanguageInvoker start, auto delete: false
11:39:11 T:2558850080  NOTICE: -->Python Interpreter Initialized<--
11:39:13 T:2865820704   ERROR: EXCEPTION: Non-Existent Control 300
11:39:49 T:2744120352  NOTICE: Thread LanguageInvoker start, auto delete: false
11:39:49 T:2744120352  NOTICE: -->Python Interpreter Initialized<--
11:39:49 T:2744120352 WARNING: CPythonInvoker(16): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by Armandoc6** [comment]
When will be released the new version? Thanks

**Comment by EMAbie** [comment]
News about a new update ? Thanks

**Comment by benticlaskaris** [comment]
updated to 1.0.3. more investigation needed for some videos but m3u and most of video are playable.
submitted to repo. will be updated in a few days.
