### ISSUE TITLE
How to login to vvvvid.it using this add-on?

### ISSUE THREAD

**Issue by ToomaiO** [evilsephiroth/plugin.video.vvvvid#3]
vvvvid.it requires a login; how to login using this Kodi add-on?
The configuration menu in the add-on (version is 1.0.2) is unavailable (gray out). This happens on a RPi with Kodi/OpenElec last version.

**Comment by benticlaskaris** [comment]
no login mechanism is implemented. currently in guest mode with cookie handling.

**Comment by ToomaiO** [comment]
Tnks
